jobs:

  packages_json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none
          
      - uses: "ramsey/composer-install@v1"
      # get package json list
      - id: output_data
        run: echo "::set-output name=matrix::$(vendor/bin/monorepo-builder packages-json)"
        
    outputs:
      matrix: ${{ steps.output_data.outputs.matrix }}

  split_monorepo:
    needs: packages_json

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.packages_json.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v2
      - name: Monorepo Split of ${{ matrix.package }}
        uses: symplify/github-action-monorepo-split@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package-directory: 'packages/${{ matrix.package }}'
          split-repository-organization: 'hexxore'
          split-repository-name: '${{ matrix.package }}'
          user-name: "Wuffz"
          user-email: "proozeboom91@gmail.com"
