name: Split Supple into packages

on:
    pull_request: null
    push:
        branches:
            - main

jobs:

  packages_json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none

      - uses: "ramsey/composer-install@v1"
      # get package json list
      - id: output_data
        run: echo "::set-output name=matrix::$(vendor/bin/monorepo-builder packages-json)"
        
    outputs:
      matrix: ${{ steps.output_data.outputs.matrix }}

  split:
    needs: packages_json

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.packages_json.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v2
      - name: Monorepo Split of ${{ matrix.package }}
        uses: Wuffz/monorepo-split-github-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package_directory: 'packages/${{ matrix.package }}'
          repository_organization: 'hexxore'
          repository_name: '${{ matrix.package }}'
          user_name: "Wuffz"
          user_email: "proozeboom91@gmail.com"
